---
#
# Ansible managed
#
repository:
  description: Trust microsofts gpg keys
  homepage: https://buluma.github.io/
  topics: microsoftrepositorykeys, ansible, molecule, tox, playbook, hacktoberfest
